### ISSUE TITLE
tag initial version

### ISSUE THREAD

**Issue by educastellano** [lifthrasiir/qr.js#1]
Tag a version so we can add it to bower

**Comment by lifthrasiir** [comment]
[Done](https://github.com/lifthrasiir/qr.js/releases/tag/2011-01-19).

**Comment by educastellano** [comment]
It should be with the format v0.0.0 or v0.1.0: &nbsp; http://semver.org/
Bower and npm require this. Sorry, I didn't mention it.

**Comment by lifthrasiir** [comment]
@educastellano Oops, I'm not well versed with bower and npm. Is the format `v0.0.20110119` an accepted one? (I believe so, but in case that it demands the lower version number...)

**Comment by educastellano** [comment]
I'm not sure either and I can't try it right now... I'll let you know tomorrow :)

**Comment by educastellano** [comment]
Tag it as you said and I'll try it out. I can't read anywhere that there is any limitation with that...

**Comment by lifthrasiir** [comment]
@educastellano Done. Can you confirm this is working?
