### ISSUE TITLE
generating GF256_MAP: i<255?

### ISSUE THREAD

**Issue by stijnsanders** [lifthrasiir/qr.js#6]
Why is there `i<255`on this line: 
https://github.com/lifthrasiir/qr.js/blob/master/qr.js#L96
and not `i<256`? That way GF256_MAP only has 255 items (no GF256_MAP[255] which should be 1, and GF256_INVMAP has 256 elements). Or is that not an issue because it's ever used?

(also are you sure about `% 255`  shouldn't that be `& 255` or `% 256`?)

**Comment by lifthrasiir** [comment]
@stijnsanders [It is very correct](https://en.wikiversity.org/wiki/Reed%E2%80%93Solomon_codes_for_coders#Multiplication_with_logarithms). (Thank god, I wasn't sure how to concisely explain that...) If you really wonder, try to replace them as you've suggested and generate a QR code---which wouldn't work.

**Comment by stijnsanders** [comment]
"bulky 64KB"?! I'm not at all worried about 64KiB of constants in my implementation! (Even twice that for mul and div) Thanks for the link, I'll need to make time to go though that thorougly...
